export default {
    public: {
        copy_success: "Copied successfully",
        copy_success_1: "URL copied, paste it in your browser to access!",
        download_success: "Saved successfully",
        button: {
            text: "Confirm",
            jump: "Skip",
            text_ok: "Confirm",
            text_ok1: "OK",
            cancel: "Cancel",
        },
        networkError: {
            text1: "Error, please try again!",
            text2: "Login expired or error occurred, please login again!",
            text3: "The requested resource does not exist!",
            mail: "Please open it in the Supe App!",
            errorProcess: "You are not in the App environment, please open the Supe App to visit!",
            errorMethodsNotDefine: "The method does not exist!",
        },
        refresh: {
            text1: "Drag down to referesh...",
            text2: "Release to referesh...",
            text3: "Loading...",
            text4: "Loading successfully~",
            text5: "noMore~",
        },
    },
    bodyActionListText: {
        action_photo: "show me a photo",
        action_video: "show me a video",
        action_kiss: "{myName} kisses {gfName}'s {parts}",
        action_touch: "{myName} touched {gfName}'s {parts}",
        action_caress: "{myName} strokes {gfName}'s {parts}",
        action_lick: "{myName} licks {gfName}'s {parts}",
        action_suck: "{myName} sucks {gfName}'s {parts}",
        action_slap: "{myName} slapped {gfName}'s {parts}",
        action_stick: "{myName} stuck {gfName}'s {parts}",
    },
    errorHandleText: {
        1701000: "Product does not exist",
        1701001: "Users have less money",
        1701002: "User has purchased",
    },
    showSoundsDialog: {
        text1: "Change Voice Model",
        text2: "Cancel",
        text3: "Confirm",
        text4: "Unlock",
        text5: "After the voice is set the next voicemessage takes effect",
        text6: "Queen",
        text7: "Lori",
        text8: "Royal sister",
        text9: "Ethereal",
        text10: "Cute",
        text11: "Validity period has expired",
    },
    vipDialog: {
        text1: "Unlock all CVIP characters for free",
        text2: "Unlock photos for free：{x}/day",
        text3: "Unlock videos for free：{x}/day",
        text4: "{x} / Year",
        text5: "{x}% OFF",
        text6: "{x} / Month",
        text7: "Subscribed",
        text8: "Time to: ",
        text9: "Free use of all VVIP voices",
        text10: "Free {x} GEM per day (value of 1USD)",
        text11: "Unlock Call privilege (pending launch)",
        text12: "Purchase successful",
        text13: "Failed purchase",
        text14: "By continuing, you agree to the ",
        text15: "Please check the agreement first",
        text16: " 'Terms of service'",
    },
    header1: {
        text1: "Recharge",
        text2: "Details",
        text3: "Details",
        text4: "Task center",
        text5: "Exchange",
        text6: "Subscription",
        text7: "$AIGF",
        text8: "Withdraw",
    },

    detailList: {
        text1: "Unlock character",
        text2: "Unlock pictures",
        text3: "Unlock videos",
        text4: "Recharge gems",
        text5: "No records",
        text6: "GEM",
        text7: "Points",
        text8: "What is points",
        // text9: "Points are interactive points of the SUPE AI Darling virtual companion platform, which are immutable interactive credentials built on the blockchain. You can earn Point rewards by completing tasks within the platform. Soon, Points can be used to redeem platform governance token airdrop rewards",
        text9: "Points are the interactive points of the SUPE AI Darling virtual companion platform. You can obtain point rewards by completing tasks within the platform.",
        text10: "OK",
    },
    recharge: {
        text1: "Gem",
        text2: "Get Gem",
        text3: "{x}% OFF",
        text4: "Recharge failed? ",
        text5: "Problem feedback",
    },
    chatList: {
        text1: "Chat",
        text2: "VIP",
    },
    chat: {
        text1: "Play failed",
        text2: "Click to play",
        text3: "Continue",
        inputText: {
            text1: "Incorrect input",
            text2: "Blank messages cannot be entered",
            text3: "Enter at least 2 characters",
            text4: "Enter up to 150 characters",
        },
        text4: "What part of her body do u wanna to {bodyActionName}",
        text5: "Cancel",
        text6: "Send",
        text7: "Please check if your browser supports Video~",
        text8: "Set a background",
        text9: "Save",
        text10: "Set successfully",
        text11: "Setting failed, please try again!",
        text12: "Waiting for you to unlock",
        text13: "Unlock",
        text14: "VIP Unlock",
        text15: "Send a message",
        text16: "Coming soon...",
    },
    chatDialog: {
        text1: "Unlock",
        text2: "You can subscribe to VIP to unlock {typeText} for free, or use Gem to unlock {typeText} individually.",
        text3: "Unlock with VIP",
        text4: "Unlock with",
        text5: "Confirm to pay <span style='color:#ff9d0a;'>{unlockNeedCoin} Gem</span> to unlock the {typeText}?",
        text6: "Insufficient Gem, recharge now!",
        text7: "VIP Free Unlock {typeText} (<span style='color:#ff9d0a;'> {unusedFreeCount}/{totalFreeCount} </span>)",
        text8: "Cancel",
        text9: "OK",
        text10: "Recharge",
        text11: "Unlock",
        text12: "Confim",
        text13: "The free times for the day have been exhausted",
        text13_1: "Unlock failed",
        text14: "Unlocked successfully",
        text14_1: "\nGet {text}",
        text14_2: "{x} Points",
        text14_3: "{x} Gems",
        text15: "Photo",
        text16: "Video",
    },
    points: {
        text1: "$SUPE Token Points",
        text2: "Daily Task",
        text3: "Daily reward",
        text4: "Go",
        text4_1: "Claim",
        text4_2: "Done",
        text5: "Chat with characters",
        text6: "Refer Task",
        text7: "Invite friends",
        text8: "/ 1 friend",
        text9: "Your refer link",
        text10: "Copy link",
        text11: "Advanced Task",
        text12: "Unlock characters",
        text13: "Claim",
        text14: "Unlock Photos",
        text15: "Social Media Task",
        text16: "Follow us on X(Twitter)",
        text17: "Done",
        text18: "Join our Discord",
    },
    exchange: {
        text1: "SUPE Points",
        text2: "Enter Exchange quantity ",
        text3: "MAX",
        text4: "Balance: 1680.0 $AIGF",
        text5: "$AIGF",
        text6: "Exchange",
        text7: "Minimum Exchange amount is 0.000000 Points ",
        text7_1: "We will deduct 0.000000 Points from the balance as Gas Fee",
        text8: "Exchange successful",
        text9: "Exchange Failed",
    },
};
