export default {
    public: {
        copy_success: "复制成功",
        copy_success_1: "网址已复制，粘贴到浏览器即可访问！",
        download_success: "保存成功",
        button: {
            text: "确定",
            jump: "跳过",
            text_ok: "确认",
            text_ok1: "好的",
            cancel: "取消",
        },
        networkError: {
            text1: "错误，请重试！",
            text2: "登录过期或出现错误，请重新登录！",
            text3: "请求的资源不存在！",
            mail: "请在Supe App内打开!",
            errorProcess: "您不在App环境内，请打开Supe App访问！",
            errorMethodsNotDefine: "方法不存在!",
        },
        refresh: {
            text1: "向下拖动刷新...",
            text2: "松开刷新...",
            text3: "加载中...",
            text4: "加载成功~",
            text5: "没有更多了~",
        },
    },
    bodyActionListText: {
        action_photo: "给我一张照片",
        action_video: "给我一个视频",
        action_kiss: "{myName} 亲了 {gfName} 的 {parts}",
        action_touch: "{myName} 触摸 {gfName} 的 {parts}",
        action_caress: "{myName} 抚摸 {gfName} 的 {parts}",
        action_lick: "{myName} 舔 {gfName} 的 {parts}",
        action_suck: "{myName} 吸 {gfName} 的 {parts}",
        action_slap: "{myName} 拍击 {gfName} 的 {parts}",
        action_stick: "{myName} 戳 {gfName} 的 {parts}",
    },
    errorHandleText: {
        1701000: "商品不存在",
        1701001: "用户余额不足",
        1701002: "用户已购买",
    },
    showSoundsDialog: {
        text1: "更改语音模型",
        text2: "取消",
        text3: "确认",
        text4: "解锁",
        text5: "设置语音后下一条语音生效",
        text6: "女王音",
        text7: "萝莉音",
        text8: "御姐音",
        text9: "空灵",
        text10: "可爱",
        text11: "已过有效期",
    },
    vipDialog: {
        text1: "解锁所有 CVIP 角色",
        text2: "解锁照片：{x}/天",
        text3: "解锁视频：{x}/天",
        text4: "{x}/ 年",
        text5: "{x}% 优惠",
        text6: "{x} / 月",
        text7: "已订阅",
        text8: "有效期到：",
        text9: "免费使用所有VVIP语音",
        text10: "每天免费 {x} 个宝石（价值 1 美元）",
        text11: "解锁通话权限（待启动）",
        text12: "购买成功",
        text13: "购买失败",
        text14: "开通前确认",
        text15: "请先勾选协议",
        text16: "《自动订阅协议》",
    },
    header1: {
        text1: "充值",
        text2: "详情",
        text3: "详情",
        text4: "任务中心",
        text5: "Exchange",
        text6: "Subscription",
        text7: "$AIGF",
        text8: "Withdraw",
    },
    detailList: {
        text1: "解锁角色",
        text2: "解锁图片",
        text3: "解锁视频",
        text4: "充值宝石",
        text5: "暂无记录",
        text6: "GEM",
        text7: "Points",
        text8: "What is points",
        // text9: "Points are interactive points of the SUPE AI Darling virtual companion platform, which are immutable interactive credentials built on the blockchain. You can earn Point rewards by completing tasks within the platform. Soon, Points can be used to redeem platform governance token airdrop rewards",
        text9: "Points are the interactive points of the  AI Darling virtual companion platform. You can obtain point rewards by completing tasks within the platform.",
        text10: "OK",
    },
    recharge: {
        text1: "宝石",
        text2: "获取宝石",
        text3: "{x}% 优惠",
        text4: "充值失败？",
        text5: "问题反馈",
    },
    chatList: {
        text1: "聊天",
        text2: "VIP",
    },
    chat: {
        text1: "播放失败",
        text2: "点击播放",
        text3: "继续播放",
        inputText: {
            text1: "输入有误",
            text2: "不可输入空白消息",
            text3: "最少输入2个字符",
            text4: "最多输入150个字符",
        },
        text4: "你想{bodyActionName}她身体的哪个部位？",
        text5: "取消",
        text6: "发送",
        text7: "请检查您的浏览器是否支持Video~",
        text8: "设置背景图",
        text9: "保存",
        text10: "设置成功",
        text11: "设置失败，请重试！",
        text12: "等待解锁",
        text13: "解锁",
        text14: "VIP解锁",
        text15: "发送消息",
        text16: "敬请期待...",
    },
    chatDialog: {
        text1: "解锁",
        text2: "您可以订阅VIP免费解锁{typeText}，也可使用Gem单独解锁{typeText}。",
        text3: "解锁VIP",
        text4: "解锁仅需",
        text5: "支付 <span style='color:#ff9d0a;'>{unlockNeedCoin} Gem</span> 即可解锁{typeText}?",
        text6: "Gem不足，请充值！",
        text7: "VIP免费解锁{typeText} (<span style='color:#ff9d0a;'> {unusedFreeCount}/{totalFreeCount} </span>)",
        text8: "取消",
        text9: "好的",
        text10: "充值",
        text11: "解锁",
        text12: "确认",
        text13: "当天免费次数已用尽",
        text13_1: "解锁失败",
        text14: "解锁成功",
        text14_1: "\n获得{text}",
        text14_2: "{x}积分",
        text14_3: "{x}Gems",
        text15: "照片",
        text16: "视频",
    },
    points: {
        text1: "$SUPE Token Points",
        text2: "Daily Task",
        text3: "Daily reward",
        text4: "Go",
        text4_1: "Claim",
        text4_2: "Done",
        text5: "Chat with characters",
        text6: "Refer Task",
        text7: "Invite friends",
        text8: "/ 1 friend",
        text9: "Your refer link",
        text10: "Copy link",
        text11: "Advanced Task",
        text12: "Unlock characters",
        text13: "Claim",
        text14: "Unlock Photos",
        text15: "Social Media Task",
        text16: "Follow us on X(Twitter)",
        text17: "Done",
        text18: "Join our Discord",
    },
    exchange: {
        text1: "SUPE Points",
        text2: "Enter Exchange quantity ",
        text3: "MAX",
        text4: "Balance: 1680.0 $AIGF",
        text5: "$AIGF",
        text6: "Exchange",
        text7: "Minimum Exchange amount is 0.000000 Points ",
        text7_1: "We will deduct 0.000000 Points from the balance as Gas Fee",
        text8: "Exchange successful",
        text9: "Exchange Failed",
    },
};
